language: c++

# attempt to install GCC 4.9, otherwise we wont have C++11 support
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.9
  - if [ "$CXX" = "g++" ]; then export CXX=g++-4.9; fi
  - sudo apt-get install -qq libcppunit-dev

compiler:
  - clang
  - gcc

env:
  - USE_TAGGING=true   GC_TYPE=generational
  - USE_TAGGING=true   GC_TYPE=mark_sweep
  - USE_TAGGING=true   GC_TYPE=copying
  
  - USE_TAGGING=false  GC_TYPE=generational CACHE_INTEGER=true
  - USE_TAGGING=false  GC_TYPE=mark_sweep   CACHE_INTEGER=true
  - USE_TAGGING=false  GC_TYPE=copying      CACHE_INTEGER=true
  
  - USE_TAGGING=false  GC_TYPE=generational CACHE_INTEGER=false
  - USE_TAGGING=false  GC_TYPE=mark_sweep   CACHE_INTEGER=false
  - USE_TAGGING=false  GC_TYPE=copying      CACHE_INTEGER=false
  


script:
    - make test
    - make bench
    - make clean
    - make unittests
